### ISSUE TITLE
改善Bot实例的构造方式

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#1909]
希望可以在之后直接在Bot类中实现一个构造方法，使可以直接使用new构造Bot实例，即
```java
Bot bot = new Bot(114514,"sodayo");
```
虽然并不清楚Mirai官方额外添加一个BotFactory和其newBot()方法作为bot实例获取方法的意图是什么（可能是Kotlin语言的因素？），但我希望可以直接用构造方法获取实例，那样更符合Java开发者的习惯
如不妥请删

**Comment by WutzuBert** [comment]
> 希望可以在之后直接在Bot类中实现一个构造方法，使可以直接使用new构造Bot实例，即 `Bot bot = new Bot(114514,"sodayo");` 虽然并不清楚Mirai官方额外添加一个BotFactory和其newBot()方法作为bot实例获取方法的意图是什么（可能是Kotlin语言的因素？），但我希望可以直接用构造方法获取实例，那样更符合Java开发者的习惯 如不妥请删

**Comment by Karlatemp** [comment]
首先接口是不能 new 的，其次推荐阅读「设计模式」

**Comment by Him188** [comment]
这是抽象工厂模式, 其实质是“提供接口，创建一系列相关或独立的对象，而不指定这些对象的具体类。”[1]. 
在 mirai 中, API 提供 Bot 接口, 使用者只需要根据 Bot 接口操作, 无需考虑其实现方式, 因此 mirai 内部在实现功能时有最大的自由度. 这也得以能隐藏具体实现而让库的维护变得更简单: 将来若要修改 Bot 实现, 使用者无需做任何修改, 而这种兼容性对一个库来说又是至关重要的.


《Effective Java》的第一个栏目 "Consider static factory methods instead of constructors" 也以另外的用途解释了使用工厂的好处 (即使 BotFactory 不是 Effective Java 所述静态工厂, 但其实际效果也是类似的): 
1. 工厂方法拥有名称
2. 工厂方法不一定每次都构造新实例
3. 工厂方法可以返回任意子类型.
4. 工厂方法返回的实例类型可以随参数而变化
5. 在工厂方法编写的时候, 其具体实现可以不一定需要存在

以下在 mirai 的设计中有体现:
3, mirai 现在会返回 QQAndroidBot, 这是针对 QQ Android 版本的实现, 将来我们可以增加对其他版本的或某个特定实现, 而不修改工厂
5, Bot 存在于 mirai-core-api, 而其实现在 mirai-core.


----
[1]: Richard Helm, Ralph Johnson, John M. Vlissides. [Design Patterns: Abstract Factory](http://www.informit.com/) (HTML). informIT. "Object Creational: Abstract Factory: Intent: Provide an interface for creating families of related or dependent objects without specifying their concrete classes."
